export enum ExperienceValue {
   ANY = "ANY",
   LESS_THAN_ONE_YEAR = "LESS THAN ONE YEAR",
   ONE_TO_THREE_YEARS = "ONE TO THREE YEARS",
   THREE_TO_FIVE_YEARS = "THREE TO FIVE YEARS",
   MORE_THAN_FIVE_YEARS = "MORE THAN FIVE YEARS",
}

export enum WorkPlace {
   ONSITE = "ONSITE",
   WORK_FROM_HOME = "WORK FROM HOME",
   HYBRID = "HYBRID",
}
